name: ESP8266 Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Add ESP8266 Board Manager URL
      run: arduino-cli config init --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

    - name: Update Core Index
      run: arduino-cli core update-index

    - name: Install ESP8266 Core
      run: arduino-cli core install esp8266:esp8266

    - name: Install Libraries
      run: |
        arduino-cli lib install "ESPAsyncTCP"
        arduino-cli lib install "ESPAsyncWebServer"
        arduino-cli lib install "ArduinoJson"

    - name: Compile Sketch
      run: arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 ${{ github.workspace }}/sonicBot/sonicBot.ino